sudo: required
language: python
python:
- '3.6'
services:
- docker
- pip
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}"
  - DOCKER_HUB_ORG="${DOCKER_HUB_ORG}"
install:
- pip install -r requirements.txt
- pip install --upgrade pytest
before_script:
- openssl aes-256-cbc -K $encrypted_38b87d0d3035_key -iv $encrypted_38b87d0d3035_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- export DB_USER="${DB_USER}"
- export DB_PASSWORD="${DB_PASSWORD}"
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy_rsa
- echo -e "FLASK_ENV=testing\nDB_USER="${DB_USER}"\nDB_PASSWORD="${DB_PASSWORD}"\nDB_URI="${DB_URI}"\nDB_NAME_PRODUCTION="${DB_NAME_PRODUCTION}"\nDB_NAME_TESTING="${DB_NAME_TESTING}"" > .env
- pytest --cov=apps tests/ || travis_terminate 1;
- echo -e "FLASK_ENV=production\nDB_USER="${DB_USER}"\nDB_PASSWORD="${DB_PASSWORD}"\nDB_URI="${DB_URI}"\nDB_NAME_PRODUCTION="${DB_NAME_PRODUCTION}"\nDB_NAME_TESTING="${DB_NAME_TESTING}"" > .env
after_script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:v1
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" && docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:v1
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_38b87d0d3035_key -iv $encrypted_38b87d0d3035_iv
  -in deploy_rsa.enc -out deploy_rsa -d
